language: node_js
node_js:
  - "node"
cache:
  yarn: true
before_install:
  - npm install -g yarn --cache-min 999999999
deploy:
  - skip_cleanup: true
    provider: script
    script: npm run build && npm run gh-pages
    on:
      branch: master
  - skip_cleanup: true
    provider: script
    script: npm run build && npm run gh-pages -- -p "$TRAVIS_BRANCH"
    on:
      all_branches: true
      condition: '"$TRAVIS_BRANCH" != "master" && "$TRAVIS_BRANCH" != "gh-pages"'
notifications:
  slack: mckinleyrice:aU792a9PkNkShDh6f6UZ9nLj